from enum import Enum


class EventType(Enum):
    NOTIFICATION = 'NOTIFICATION'
    FAQ_CATEGORY_REQUEST = 'FAQ_CATEGORY_REQUEST'
    FAQ_CATEGORY_REPLY = 'FAQ_CATEGORY_REPLY'
    FAQ_QUESTION_REQUEST = 'FAQ_QUESTION_REQUEST'
    FAQ_QUESTION_REPLY = 'FAQ_QUESTION_REPLY'
